Automated test #1
oteplova/AT_Bootcamp pull request #15
Opened 2018-02-19 22:49 UTC by oteplova

#13

2018-02-21 09:52 UTC, extsoft requested changes
@oteplova please solve the comments.

2018-02-21 09:52 UTC, extsoft commented on src/main/java/net/comments/Test1.java
> +        final String page = this.driver().getPageSource();
It's bug if you load the page content before even page is open (line 21). That's why assertion on line 29 won't work correctly.

2018-02-21 09:52 UTC, extsoft commented on src/main/java/net/comments/Test1.java
> +        String commentsText = "Test text";
Make `final`.

2018-02-21 09:52 UTC, extsoft commented on src/main/java/net/comments/Test1.java
> +        String number = "31";
Make `final`.

2018-02-21 09:52 UTC, extsoft commented on src/main/java/net/comments/Test1.java
> +        String savedNumber, savedCommentsText, inactivationSign, categoryName;
Don't use batch assignment. Create a variable when you are going to use it. For instance, in line 31.

2018-02-21 09:52 UTC, extsoft commented on src/main/java/net/comments/Test1.java
> +        MatcherAssert.assertThat("Comments text does not contain " + savedCommentsText, savedCommentsText.contains(savedCommentsText));
Actual and Expected are the same.

2018-02-22 10:00 UTC, oteplova commented
@extsoft I've fixed comments. Please check

2018-02-24 09:33 UTC, extsoft approved these changes
@oteplova great!

2018-02-24 09:34 UTC, merged