#20 Automated Test #2
oteplova/AT_Bootcamp pull request #21
Opened 2018-03-01 21:26 UTC by oteplova

Test #2: 
User can duplicate a comment (comment is created with all data from parent's comment and unique number)

2018-03-01 21:26 UTC, oteplova commented
@extsoft please check.

2018-03-02 00:34 UTC, oteplova commented
@extsoft  I've mistakenly push changes from branch #22 to branch #20 and I don't know how to revert them. What I should do in such cases?

2018-03-02 06:53 UTC, oteplova commented
@extsoft  I've reverted changes for Test #3

2018-03-02 11:11 UTC, extsoft requested changes
@oteplova Please fix my comments.

2018-03-02 11:11 UTC, extsoft commented on src/main/java/net/comments/objects/CommentTable.java
> +    String getTextSelectedComment(int commentNumber);
Please rename methods as I can't understand what it does.

2018-03-02 11:11 UTC, extsoft commented on src/main/java/net/comments/objects/BCommentManagerDuplicate.java
>  public class BCommentManagerDuplicate implements CommentManager {
Why do you use a separate class for implementing each interface methods? Please implement 3 methods in the one class.

2018-03-02 11:11 UTC, extsoft commented on src/main/java/net/comments/objects/BCommentManagerDuplicate.java
> +        this.driver.findElement(By.xpath("//*[@id = \"Number\"]")).sendKeys(newCommentNumber);
You need use separate class to work with updating comments data. `Save & Return` is only a button to save changes.

2018-03-02 11:11 UTC, extsoft commented
> @extsoft I've mistakenly push changes from branch #22 to branch #20 and I don't know how to revert them. What I should do in such cases?

@oteplova is it still relevant?

2018-03-02 11:27 UTC, oteplova commented
> @oteplova is it still relevant?

No, I've already resolved this issue.

2018-03-03 23:44 UTC, oteplova commented
@extsoft I've fixed comments. Please check.

2018-03-04 11:36 UTC, extsoft approved these changes
@oteplova great job!

2018-03-04 11:36 UTC, merged