#28 Test#5
oteplova/AT_Bootcamp pull request #29
Opened 2018-03-05 23:23 UTC by oteplova

Test#5: User can delete multiple comments (> 1)

2018-03-06 05:28 UTC, extsoft requested changes

2018-03-06 05:28 UTC, extsoft commented on src/main/java/net/comments/ft/Test2.java
> +        int[] commentNumber = {5};
Why do you use an array here?

2018-03-06 05:28 UTC, extsoft commented on src/main/java/net/comments/ft/Test3.java
> +        int[] commentNumber = {1};
Why do you use an array here?

2018-03-06 05:28 UTC, extsoft commented on src/main/java/net/comments/ft/Test4.java
> +        int[] commentNumber = {1};
Why do you use an array here?

2018-03-06 05:28 UTC, extsoft commented on src/main/java/net/comments/ft/Test5.java
> +        page.getCurrentComments().selectComment(commentNumbers);
Why do you use an array here? If you need to select 2 comments, use method twice.

2018-03-06 05:28 UTC, extsoft commented on src/main/java/net/comments/objects/BCommentTable.java
> +    public void selectComment(int[] commentNumbers) {
If you want to have a method to select several comments, create it. Don't try  to have [GOD methods](https://en.wikipedia.org/wiki/God_object).

2018-03-06 16:39 UTC, oteplova commented
@extsoft I've fixed the comments. Please check.

2018-03-09 11:02 UTC, extsoft requested changes

2018-03-09 11:02 UTC, extsoft commented on src/main/java/net/comments/objects/BCommentTable.java
> +            this.driver.findElement(By.xpath(String.format("//*[@name = \"SelectedId\" and @value = \"%s\"]", commentNumber + 1))).click();
Use `this. selectComment(commentNumber)` instead of.

2018-03-09 15:48 UTC, oteplova commented
@extsoft I've fixed the comment. Please review.

2018-03-12 16:08 UTC, oteplova commented
@extsoft  Could you please check my chsnges?

2018-03-12 16:35 UTC, extsoft approved these changes
@oteplova great job

2018-03-12 16:35 UTC, merged